kind: Service
apiVersion: v1
metadata:
  name: from-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: from-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30101